//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCare.WebApp.Modules.Laboratory.Pages.CapMa {
    
    
    public partial class CapMa {
        
        /// <summary>
        /// DichVuXetNghiem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iCare.WebApp.Modules.Laboratory.Pages.CapMa.DichVuXetNghiem DichVuXetNghiem;
        
        /// <summary>
        /// DSBNCho control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iCare.WebApp.Modules.Laboratory.Pages.CapMa.DSBNCho DSBNCho;
        
        /// <summary>
        /// DSBNDaCapMa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::iCare.WebApp.Modules.Laboratory.Pages.CapMa.DSBNDaCapMa DSBNDaCapMa;
    }
}
